theme = "plain"
icons = "none"

#[[block]]
#block = "custom"
#command = "/home/cole/.config/sway/scripts/status-termtime.sh"

#[[block]]
#block = "custom"
#command = "/home/cole/.config/sway/scripts/status-outputs.sh"
#interval = 1

[[block]]
block = "backlight"

[[block]]
block = "sound"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}Â°"

[[block]]
block = "cpu"
frequency = true

[[block]]
block = "memory"
format_mem = "{Mup}%"

[[block]]
block = "battery"
format = "{percentage}% {time}"

[[block]]
block = "time"
format = "%a-%_d %H:%M:%S "

#[[block]]
#block = "custom"
#command = "/home/cole/.config/sway/scripts/status-time.sh"

