root:
  askformore: false
  autoclip: false
  autoimport: true
  autosync: true
  check_recipient_hash: false
  cliptimeout: 45
  concurrency: 1
  editrecipients: false
  nocolor: false
  noconfirm: true
  nopager: true
  notifications: true
  path: gpgcli-gitcli-fs+file:///home/cole/.password-store
  recipient_hash:
    .gpg-id: 3078393735383037384445353330383330380aa69f73cca23a9ac5c8b567dc185a756e97c982164fe25859e0d1dcc1475c80a615b2123af1f5f94c11e3e9402c3ac558f500199d95b6d3e301758586281dcd26
  safecontent: false
  usesymbols: false
mounts: {}
