name: "clean-actions"
on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:
jobs:
  "clean-actions":
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes ca-references
          extra-binary-caches = https://cache.nixos.org https://colemickens.cachix.org https://nixpkgs-wayland.cachix.org https://unmatched.cachix.org https://nix-community.cachix.org https://cache.nixos.org
          extra-trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= colemickens.cachix.org-1:bNrJ6FfMREB4bd4BOjEN85Niu8VcPdQe4F4KxVsb/I4= nixpkgs-wayland.cachix.org-1:3lwxaILxMRkVhehr5StQprHdEo4IrE8sRho9R9HOLYA= unmatched.cachix.org-1:F8TWIP/hA2808FDABsayBCFjrmrz296+5CQaysosTTc= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: shell
      run: nix develop '.#ci' -c true
    - name: init
      run: nix develop '.#ci' -c .github/init.nu
    - name: clean-actions
      env: { GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}" }
      run: nix develop '.#ci' -c .github/clean-actions.nu
